### ISSUE TITLE
Linking to OpenCV needed

### ISSUE THREAD

**Issue by robinloujun** [ethz-asl/kitti_to_rosbag#11]
Hallo,
when compiling the package I find the executable tiny_disp_view needs linking to OpenCV. 
So the [CMakeLists.txt](https://github.com/ethz-asl/kitti_to_rosbag/files/2514507/CMakeLists.txt)

**Comment by gkouros** [comment]
It is fixed in branch fix/open_cv https://github.com/ethz-asl/kitti_to_rosbag/tree/fix/open_cv
