### ISSUE TITLE
abort (core dumped)

### ISSUE THREAD

**Issue by VarunUmesh1407** [ethz-asl/kitti_to_rosbag#8]
Hi all, 
I am trying  to convert a kitti dataset to ros bag file. but i am getting the error described below.
please help., 

Timestmap map for pose:
terminate called after throwing an instance of 'rosbag::BagIOException'
  what():  Error opening file: datasets/kitti/2011_09_26
*** Aborted at 1504541712 (unix time) try "date -d @1504541712" if you are using GNU date ***
PC: @     0x7fb00104ac37 gsignal
*** SIGABRT (@0x3e800002801) received by PID 10241 (TID 0x7fb00303e9c0) from PID 10241; stack trace: ***
    @     0x7fb00104acb0 (unknown)
    @     0x7fb00104ac37 gsignal
    @     0x7fb00104e028 abort
    @     0x7fb001653535 __gnu_cxx::__verbose_terminate_handler()
    @     0x7fb0016516d6 (unknown)
    @     0x7fb001651703 std::terminate()
    @     0x7fb001651922 __cxa_throw
    @     0x7fb00192e1ca rosbag::ChunkedFile::open()
    @     0x7fb00192e375 rosbag::ChunkedFile::openWrite()
    @     0x7fb001912a3d rosbag::Bag::openWrite()
    @     0x7fb001918185 rosbag::Bag::open()
    @           0x409891 kitti::KittiBagConverter::KittiBagConverter()
    @           0x409136 main
    @     0x7fb001035f45 __libc_start_main
    @           0x4096ea (unknown)
Aborted (core dumped)

**Comment by helenol** [comment]
Looks like it can't open the bag file... make sure the file path you feed in is correct. Looks like the file you're trying to write to is: "datasets/kitti/2011_09_26", make sure to give it a full path with a .bag extension in an existing directory.

**Comment by Varun1407** [comment]
Hi @helenol  , 

I am using the instruction as mentioned in the readme file .
rosrun kitti_to_rosbag kitti_rosbag_converter ~/data/kitti/2011_09_26 ~/data/kitti/2011_09_26/2011_09_26_drive_0035_sync ~/data/kitti/2011_09_26/2011_09_26_drive_0035_sync/testbag.bag

but still it is throwing the same error that it cannot open the dataset file.

**Comment by CtfChan** [comment]
Hey I'm encountering the same issue as well right now. Has anyone come up with a solution?

**Comment by rdube** [comment]
@CtfChan see the comment of @helenol above. Also make sure that you have sufficient space on your hard drive.

**Comment by CtfChan** [comment]
Got it fixed. Thanks rdube (y)
